

funciones
```{r}


length(linkedin)
head(linkedin)
class(linkedin)
tail(linkedin)
```


Funciones
```{r}

avg_li=mean(linkedin)
avg_li
sum(linkedin)



```

```{r}
pow_two=function(arg)
{
  arg**2
  
  
  
}

pow_two(2)

sum_abs=function(arg1,arg2){
  abs(arg1)+abs(arg2)
}
  

sum_abs(-2,3)

hello = function()


```




```{r}
interpret =function(num_views) {
  if (num_views>15){
    print("popular")
    return(num_views)
  }else{
    print("more visible")
    return(0)
  }
}

interpret(linkedin[2])
interpret_all = function(views,return_sum=TRUE){
  count=0
  for (v in views){
    count = count + interpret (v)
  }
    if (return_sum){
      return(count)
      
      
    }else {
      return(NULL)
    }
    
    
    
}
interpret_all(linkedin)
```

```{r}
interpret_all(FALSE,linkedin)



```


```{r}
interpret_all(linkedin)
```


```{r}
library(ggplot2)
mtcars
qplot(mtcars$wt,mtcars$hp)
```

familia apply


lapply

```{r}
pioneers = c("gauss:1777","Bayes:1702","pascal:1823", "pearson:1857")

split_match = strsplit(pioneers,split = ":")
split_match

Split_low = lapply(split_match,tolower)

select_first = function(x){
  x[2]
}

names = lapply(Split_low,select_first)
select_second=function(x){
  
  x[2]
  
}

```
lapply y anonymous

```{r}

Split_low
names = lapply((Split_low, function(x)))


```



```{r}
vec1=c(3,8,7,6)
vec2=
```



vapply
```{r}
basics = function(x){
  c(min=min(x),mean=mean(x),max=max(x))
}
temp
vapply(temp,basics,numeric(3))

```

matematicas

```{r}
errors = c(1.9,-2.6,4.0,-9.5,-3.4,)



```





